PageLayoutExample:

<PageLayoutExample@PageLayout>:
    MainWidget:
    ScrollViewExample:


<ScrollViewExample@ScrollView>:
    GridLayoutExample:
        size_hint: 1, None
        height: self.minimum_height



<MainWidget>:
    Button:
        text: "Hello"
        size: "100dp", "80dp"
        pos: "100dp", "200dp"
        color: 1, 0, 0, 1

    Label:
        text: "Hello"
        size: "100dp", "80dp"
        pos: "300dp", "200dp"